#!/usr/bin/python3

import sys


file_name = sys.argv[1] or None

def factorize(number):
	counter = 2
	while number > 1 and number != counter:
		if number % counter == 0:
			print(f"{number}={number // counter}*{counter}")
			break
		else:
			counter += 1


def main():
	if file_name:
		try:
			with open(file_name, mode="r") as f:
				numbers = [int(number.strip()) for number in f.readlines()]
		except FileNotFoundError:
			print("Invalid file provided.")
		else:
			for number in numbers:
				factorize(number)
	else:
		print("File not provided.")


if __name__ == "__main__":
	main()
